Don't call core_set_thread_initializer if not defined
dashpay/bls-signatures pull request #13
Opened 2021-03-08 05:05 UTC by kittywhiskers

## Description

`core_set_thread_initializer` is only defined if macro `MULTI != RELIC_NONE` evaluates false. 

It evaluates as true on some systems and since we cannot inherit relic's macros when compiling BLS,
we add an additional check to see if the function is defined (inheriting the macro's evaluation) and decide
accordingly if we make a call to it or not.

Tested on `Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64`

2021-03-08 12:50 UTC, xdustinface requested changes
Thanks for the PR but there are some issues:

1. `#ifdef core_set_thread_initializer` doesn't work at all because `core_set_thread_initializer` is a function, not a define so this evaluates to `false` no matter if `core_set_thread_initializer` function exists or not.
2. It's still in any case required to call `relic_core_initializer` to initialize relic.
3. Tests should be adjusted too.

See f208c6764a89959890f3f7970812eb27cd6bba00 for a fix and test adjustment. 

--- 

> since we cannot inherit relic's macros when compiling BLS

Why not? They are defined in `relic_conf.h` which is (indirectly) included here. 

--- 

Can you please also open this PR to https://github.com/Chia-Network/bls-signatures?

2021-03-08 13:32 UTC, kittywhiskers commented
> Why not? They are defined in relic_conf.h which is (indirectly) included here

I didn't know that, [now I do](https://www.youtube.com/watch?v=GD6qtc2_AQA). I'm completely unfamiliar with the codebase and I just did whatever I thought would get it to compile!

> #ifdef core_set_thread_initializer doesn't work at all because core_set_thread_initializer is a function, not a define so this evaluates to false no matter if core_set_thread_initializer function exists or not

Might've well just done an `#if 0` :P 

> Can you please also open this PR to https://github.com/Chia-Network/bls-signatures?

Sure! I'll link them back to this PR!

----

I'll cherry pick your commit to the branch and try again. Thanks for reviewing (this admittedly ill-done PR ~~but it's the thought that counts, right?~~)

2021-03-08 13:57 UTC, xdustinface approved these changes
ACK

2021-03-31 14:36 UTC, UdjinM6 approved these changes
utACK

2021-04-05 17:37 UTC, xdustinface commented
Closing because its included in #19

2021-04-05 17:37 UTC, closed without merging