fix: the JS bundle script and bindings
dashpay/bls-signatures pull request #47
Opened 2022-10-19 08:31 UTC by antouhou

2023-01-31 08:58 UTC, shumkov requested changes

2023-01-31 08:58 UTC, shumkov commented on js-bindings/CMakeLists.txt
> +set_target_properties(blsjstmp PROPERTIES LINK_FLAGS "--bind -Oz --closure 1 -s MODULARIZE=1 -s NODEJS_CATCH_EXIT=0 -s NODEJS_CATCH_REJECTION=0")
Why do we disable catch rejection and catch exit?

2023-02-06 10:40 UTC, shumkov commented on js-bindings/CMakeLists.txt
> +set_target_properties(blsjstmp PROPERTIES LINK_FLAGS "--bind -Oz --closure 1 -s MODULARIZE=1 -s NODEJS_CATCH_EXIT=0 -s NODEJS_CATCH_REJECTION=0")
We agreed to set `NODEJS_CATCH_EXIT` and `NODEJS_CATCH_REJECTION` to `1` according to https://github.com/emscripten-core/emscripten/issues/11532

2023-02-06 13:15 UTC, shumkov approved these changes
👍

2023-02-06 13:51 UTC, shuplenkov approved these changes

2023-02-07 10:44 UTC, merged