fix: rid of UB and memory leak based on clang warnings
dashpay/bls-signatures pull request #67
Opened 2023-02-20 17:23 UTC by knst

- fixed UB with reading unitialized data from buffer and compare by memcmp
 - fix: add missing `final` and virtual destructor to avoid memory leak.
    
It also removes several clang's warnings during build.

2023-02-23 17:10 UTC, knst commented
> I think this should be done upstream

 - https://github.com/Chia-Network/bls-signatures/pull/358
 - https://github.com/Chia-Network/bls-signatures/pull/359

2023-04-25 11:17 UTC, knst commented
@PastaPastaPasta that 2 PR are dead in Chia's repo.

Can you review and merge this PR instead waiting them get merged and backported later?

2023-04-25 15:14 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-05-25 22:08 UTC, UdjinM6 requested changes
should backport https://github.com/Chia-Network/bls-signatures/pull/370 and https://github.com/Chia-Network/bls-signatures/pull/371

2023-06-10 19:28 UTC, UdjinM6 commented
superseded by #83

2023-06-10 19:28 UTC, closed without merging