readme: Fix and expand build status
dashpay/bls-signatures pull request #7
Opened 2020-10-30 15:45 UTC by xdustinface

Based on #6 + it points to the status of `develop` which we don't have at the time of PR opening.

2020-11-17 19:15 UTC, UdjinM6 requested changes

2020-11-17 19:15 UTC, UdjinM6 commented on README.md
> +*Travis* | [![Travis-Master](https://travis-ci.org/dashpay/bls-signatures.svg?branch=master)](https://travis-ci.org/dashpay/bls-signatures) | [![Travis-Develop](https://travis-ci.org/dashpay/bls-sign
```suggestion
*Travis* | [![Travis-Master](https://travis-ci.com/dashpay/bls-signatures.svg?branch=master)](https://travis-ci.com/dashpay/bls-signatures) | [![Travis-Develop](https://travis-ci.com/dashpay/bls-signatures.svg?branch=develop)](https://travis-ci.com/dashpay/bls-signatures)
```

2020-11-17 19:31 UTC, UdjinM6 approved these changes
utACK (rich diff looks good)

2020-11-19 16:27 UTC, PastaPastaPasta approved these changes
utACK

2020-11-19 16:27 UTC, merged